### ISSUE TITLE
Validation issue for custom install location / Game Data in Steam

### ISSUE THREAD

**Issue by olivervbk** [cwoac/TTS-Manager#17]
I have TTS installed in
E:/SteamLibrary/steamapps/common/Tabletop Simulator

and the Game Data folder is 
E:\SteamLibrary\steamapps\common\Tabletop Simulator\Tabletop Simulator_Data

It doesn't validate.

**Comment by bobpaul** [comment]
Can you provide a list of steps to reproduce? Be sure to include whether you're running the cli or the gui and what options you used, buttons you clicked etc.
